name: Deployment to heroku

on: 
  push
   
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
    - name: git checkout
      uses: actions/checkout@v3
    - name: heroku deploy
      uses: onekiloparsec/heroku-node-deploy-subfolder@v1.1.0
      with:
        api_key: ${{secrets.HEROKU_API_KEY}}
        email: ${{secrets.HEROKU_EMAIL}}
        app_name: transports-server-12
        heroku_branch: "main"
        subfolder: "dist"