name: Deployment to heroku

on: 
  push
   
jobs:
  runs-on: ubuntu-latest
  steps:
    - name: git checkout
      uses: actions/checkout@v3
    - name: deploy to heroku
      run: git push heroku main